---
title: '**CSC487**: Data Mining - Homework #3'
output:
  pdf_document:
    latex_engine: pdflatex
    extra_dependencies:
    - xcolor
    - hyperref
    - tikz
  word_document: default
  html_document:
    df_print: paged
fontsize: 12pt
graphics: yes
geometry: "left=1cm,right=1cm,top=1cm,bottom=2cm"
---

```{=latex}
\newcommand{\XB}{\color{black}}
\newcommand{\XBB}{\color{blue}}
\newcommand{\XV}{\color{violet}}
\newcommand{\XR}{\color{red}}

\begin{center}
  \XV\textit{\large{\href{https://github.com/casonk}{Cason Konzer}}}\XB \\
\end{center}
\hrulefill
\hfill
\newpage
```

```{r include=FALSE}
options(knitr.graphics.error = FALSE)

library(knitr)
library(ggplot2)
```

```{python include=FALSE}
import pandas as pd
import numpy as np
```


### 1. Suppose that we have age data including the following numbers in sorted order. *(25 points total)*
[13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70]

---

Let us first load in the data...

```{python}
# load in the data...
nums = [13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 
        25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70]
df1 = pd.DataFrame()
df1['nums'] = nums

# preview the data...
df1
```

```{=latex}

\newpage
```

#### a.) Use smoothing by bin means to smooth the above data, using a bin depth of 3. Illustrate your steps. Comment on the effect of this technique for the given data. *(5 points)*

--- 

```{python}
# length of data.
l = df1.size
l
```

```{python}
# cut idx.
q = int(l/3)
q
```

```{python}
# binning & averaging.
df1['3bin_mean'] = 0
df1['3bin_mean'].iloc[0:q] = df1['nums'].iloc[0:q].mean()
df1['3bin_mean'].iloc[q:2*q] = df1['nums'].iloc[q:2*q].mean()
df1['3bin_mean'].iloc[2*q:l] = df1['nums'].iloc[2*q:l].mean()

df1
```


```{=latex}
This technique \XBB generalizes \XB our data into 3 groups, increasing our previous minimum and decreasing our previous maximum.

\hrulefill
```

#### b.) How can you determine outliers in the data? *(5 points)*

---

Outliers are typically determines by the Interquartile Range (IQR). If a value is outside 1.5 times the IQR we call it an outlier.

```{python}
# summary statistics.
df1.describe()
```

```{python}
# IQR.
q1 = df1.describe()['nums']['25%']
q2 = df1.describe()['nums']['75%']
```

```{python}
# 1.5 IQR.
min_allowed = q1/1.5
min_allowed
```

```{python}
# 1.5 IQR.
max_allowed = q2*1.5
max_allowed
```

```{python}
# Mask the dataframe.
outliers = df1['nums'][(df1['nums'] < min_allowed) | (df1['nums'] > max_allowed)]
outliers
```

```{=latex}
As seen in part a.) $l=27$, thus our smallest value, idx 0, and our largest value, idx 27, are shown here. \XBB $ 13 \ \& \ 17 $ \XB would generally be accepted as outliers.

\hrulefill
```

```{=latex}

\newpage
```

#### c.) Use min-max normalization to transform the value $35$ for age onto the range [0.0, 1.0]. *(5 points)*

---

```{python}
# Create min max scaling function.
def min_max_scaler(val):
    r = df1['nums'].max() - df1['nums'].min()
    return (val - df1['nums'].min()) / r

# Scale 35.
min_max_scaler(35)
```

```{=latex}
We can see min-max normalization transforms $35$ into \XBB 0.386 \XB.

\hrulefill
```

#### d.) Use z-score normalization to transform the value $35$ for age? *(5 points)*

---

```{python}
# Create z score scaling function.
def z_score_scaler(val):
    return (val - df1['nums'].mean()) / df1['nums'].std()

# Scale 35.
z_score_scaler(35)
```

```{=latex}
We can see z-score normalization transforms $35$ into \XBB 0.389 \XB.

\hrulefill
```

#### e.) Use normalization by decimal scaling to transform the value $35$ for age. *(5 points)*

---

```{python}
# Create decimal scaling function.
def decimal_scaler(val):
    return val/100

# Scale 35.
decimal_scaler(35)
```

```{=latex}
We can see normalization transforms by decimal scaling $35$ into \XBB 0.35 \XB.

\hrulefill
```

```{=latex}

\newpage
```

### 2. Write a function in your preferred language which can take a data vector and do min-max normalization by transforming data onto a desired range. *(25 points)*

---

```{python}
# Use data from q1 as example.
a = np.array(nums)

# preview the data...
a
```

```{python}
# Define variable min max scaler.
def min_max_mapper(np_array, new_min, new_max):
    mn = np_array.min()
    mx = np_array.max()
    r = mx - mn
    a = (np_array - mn) / r
    new_r = new_max - new_min 
    return (a * new_r) + new_min

# Test with data.
min_max_mapper(a, -10, 10)
```

```{=latex}
Solution writted in \XBB python \XB dependent on \XBB numpy \XB.

\hrulefill
```

```{=latex}

\newpage
```

### 3. Using information gain on the data in Table 1, do calculations for two levels of a decision tree which decides whether a person is senior or junior. *(25 points)*

---

```{python}
# load in the data...
table1 = {
    'department' : ['sales', 'sales', 'sales', 'systems', 
                    'systems', 'systems', 'systems', 'marketing', 
                    'marketing', 'secretary', 'secretary'],
    'age' : ['31_35', '26_30', '31_35', '21_25', 
             '31_35', '26_30', '41_45', '36_40', 
             '31_35', '46_50', '26_30'],
    'salary' : ['46K_50K', '26K_30K', '31K_35K', '46K_50K', 
                '66K_70K', '46K_50K', '66K_70K', '46K_50K', 
                '41K_45K', '36K_40K', '26K_30K'],
    'status' : ['senior', 'junior', 'junior', 'junior', 
                'senior', 'junior', 'senior', 'senior', 
                'junior', 'senior', 'junior'],
    'count' : [30, 40, 40, 20, 5, 3, 3, 10, 4, 4, 6]
}
df2 = pd.DataFrame(table1)

# preview the data...
df2
```

```{python}
# Create information gain function.
def gainer(df, label, counts):
    # Create DataFrame for storing gain.
    gainz = pd.DataFrame(index=['entropy', 'gain'])

    # Find total observations.
    total = df[counts].sum()
    print('{} total observations'.format(total))
    print()
    
    # Find total observations per label.
    sum0 = pd.DataFrame(
        df.groupby(by=label)[counts].apply(
            lambda x: x.sum()
        ))
    print('observations per label')
    print(sum0)
    print()

    # Find label probabilities.
    p_label = sum0 / total
    print('label probabilities')
    print(p_label)
    print()

    # Find total entropy.
    total_entrop = float((-p_label * np.log2(p_label)).sum())
    print('total entropy')
    print(total_entrop)
    print()

    # Find attribute columns.
    cols = df.columns.drop(label)
    cols = cols.drop(counts)
    print('attribute columns')
    print(cols)
    print()

    for col in cols:
        # Find total observations per bin.
        sum1 = pd.DataFrame(
            df.groupby(by=col)[counts].apply(
                lambda x: x.sum()
            ))

        # Find label totals per bin.
        sum2 = pd.DataFrame(
            df.groupby(by=[col, label])[counts].apply(
                lambda x: x.sum()
            ))

        # Solve for entropy per class
        p_label_class = sum2 / sum1
        H = -p_label_class * np.log2(p_label_class)

        # Solve for expected entropy per class
        entrop = pd.DataFrame(
            H.unstack().apply('sum', axis=1), columns=['H']
            )
        entrop['P[class]'] = sum1 / total
        entrop['E[H]'] = entrop['H'] * entrop['P[class]']
        entropy = entrop['E[H]'].sum()

        gain = total_entrop - entropy
        gainz[col] = [entropy, gain]

    return gainz

# calculate information gain on status at level 1.
g1 = gainer(df2, 'status', 'count')
g1.T
```


```{=latex}
As \XBB salary \XB has the most information gain we will use it for the level 1 split.

\hrulefill
```

```{=latex}

\newpage
```

```{python, results=FALSE}
g2 = df2.groupby('salary').apply(
    lambda x: gainer(x.drop('salary', axis=1), 'status', 'count')
)
```


```{python}
g2
```

```{=latex}
As \XBB department \XB and \XBB age \XB have equal information gain we can use \XBB either \XB for the level 2 split. 

\hrulefill
```

```{=latex}

\newpage
```

### 4. Using the decision tree, generate if-then rules. *(25 points)*

---

```{=latex}

\begin{center}
    \begin{tikzpicture}[scale=2.75]
        \draw (0,0) circle (1);
        \draw (-2,-2) circle (1);
        \draw (2,-2) circle (1);
        \draw[thick, ->] (-0.5,-0.5) to (-1.5,-1.5);
        \draw[thick, ->] (0.5,-0.5) to (1.5,-1.5);
        \node [] at (0,0) {$level_{1}$};
        \node [below left, blue] at (-1.5,-0.25) {$salary < 46K$};
        \node [below right, blue] at (1.5,-0.25) {$salary > 50K$};
        \node [red] at (-2,-2) {$junior$};
        \node [red] at (2,-2) {$senior$};
        \draw (0,-4) circle (1);
        \draw[thick, ->] (0,-0.75) to (0,-3.25);
        \node [] at (0,-4) {$level_{2}$};
        \draw (-2,-6) circle (1);
        \draw (2,-6) circle (1);
        \draw[thick, ->] (-0.5,-4.5) to (-1.5,-5.5);
        \draw[thick, ->] (0.5,-4.5) to (1.5,-5.5);
        \node [below left, blue] at (-1.5,-4.25) {$department = systems$};
        \node [below right, blue] at (1.5,-4.25) {$department \ne systems$};
        \node [red] at (-2,-6) {$junior$};
        \node [red] at (2,-6) {$senior$};
    \end{tikzpicture}

    Tree 1: Level 2 Split on Department
    
    
    \begin{tikzpicture}[scale=2.75]
        \draw (0,0) circle (1);
        \draw (-2,-2) circle (1);
        \draw (2,-2) circle (1);
        \draw[thick, ->] (-0.5,-0.5) to (-1.5,-1.5);
        \draw[thick, ->] (0.5,-0.5) to (1.5,-1.5);
        \node [] at (0,0) {$level_{1}$};
        \node [below left, blue] at (-1.5,-0.25) {$salary < 46K$};
        \node [below right, blue] at (1.5,-0.25) {$salary > 50K$};
        \node [red] at (-2,-2) {$junior$};
        \node [red] at (2,-2) {$senior$};
        \draw (0,-4) circle (1);
        \draw[thick, ->] (0,-0.75) to (0,-3.25);
        \node [] at (0,-4) {$level_{2}$};
        \draw (-2,-6) circle (1);
        \draw (2,-6) circle (1);
        \draw[thick, ->] (-0.5,-4.5) to (-1.5,-5.5);
        \draw[thick, ->] (0.5,-4.5) to (1.5,-5.5);
        \node [below left, blue] at (-1.5,-4.25) {$age < 31$};
        \node [below right, blue] at (1.5,-4.25) {$age \ge 31$};
        \node [red] at (-2,-6) {$junior$};
        \node [red] at (2,-6) {$senior$};
    \end{tikzpicture}
    
    Tree 2: Level 2 Split on Age
    
\end{center}

```

```{=latex}
\newpage

For both tress we have $ level_{1} $ if-then rules as follows \dots

\begin{itemize} \XBB
    \item $ If \quad salary < 46K \quad then \quad label = junior $
    \item $ If \quad salary > 50K \quad then \quad label = senior $
    \item $ Else \quad continue $
\end{itemize} \XB

For Tree 1 we have $ level_{2} $ if-then rules as follows \dots
\begin{itemize} \XBB
    \item $ If \quad department = systems \quad then \quad label = junior $
    \item $ Else \quad then \quad label = senior $
\end{itemize} \XB

For Tree 2 we have $ level_{2} $ if-then rules as follows \dots
\begin{itemize} \XBB
    \item $ If \quad age < 31 \quad then \quad label = junior $
    \item $ Else \quad then \quad label = senior $
\end{itemize} \XB

\hrulefill
```